# Generated by Django 5.2.4 on 2025-07-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='feedback',
            field=models.TextField(blank=True, help_text='AI-generated feedback for the answer', null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='score',
            field=models.FloatField(blank=True, help_text='Score for this specific answer (e.g., out of 5)', null=True),
        ),
    ]
