# Generated by Django 5.2.4 on 2025-07-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_studentanswer_feedback_studentanswer_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='originality_report',
            field=models.TextField(blank=True, help_text='AI-generated report on text originality', null=True),
        ),
    ]
