# Generated by Django 5.2.4 on 2025-07-19 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('grade_level', models.CharField(help_text="e.g., '6th Grade'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('short_answer', 'Short Answer')], max_length=20)),
                ('options', models.JSONField(blank=True, help_text="For MCQs, e.g., {'A': 'Option 1'}", null=True)),
                ('correct_answer', models.TextField(help_text="For MCQs, just the letter 'A'. For short answers, the model answer.")),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='worksheets.worksheet')),
            ],
        ),
    ]
